### ISSUE TITLE
isn't there a way to check if number has whatsapp ?

### ISSUE THREAD

**Issue by yazeed44** [sumppen/WhatsApi4J#4]
Hi , i'm thinking of using this API to make a whatsapp for desktop

but there's a problem , the user will add a bunch of numbers into the program , and i can't figure out how to check if those number hasn't got whatsapp ?

**Comment by drenda** [comment]
This would be a nice feature but I don't know if it is provided from the api.

**Comment by sumppen** [comment]
Implemented contact sync, which returns if the contacts have whatsapp or not

**Comment by drenda** [comment]
Fantastic the sync method. Is not very clear how to get the response. Now seems that the response in received in EventManager.
But the typical use case (server side) is to check if a contact is a whatapp user and if true send the message, otherwise fails the send. So my question is: can I call sync method as a blocking request and obtais the result to understand if the user is a whatsapp user?

Thanks
